// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_houses_id_ from "./routes/api/houses/[id].ts";
import * as $api_houses_index from "./routes/api/houses/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Fetcher from "./islands/Fetcher.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $HouseForm from "./islands/HouseForm.tsx";
import * as $HouseRow from "./islands/HouseRow.tsx";
import * as $HouseTable from "./islands/HouseTable.tsx";
import * as $Modal from "./islands/Modal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/houses/[id].ts": $api_houses_id_,
    "./routes/api/houses/index.ts": $api_houses_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Fetcher.tsx": $Fetcher,
    "./islands/Header.tsx": $Header,
    "./islands/HouseForm.tsx": $HouseForm,
    "./islands/HouseRow.tsx": $HouseRow,
    "./islands/HouseTable.tsx": $HouseTable,
    "./islands/Modal.tsx": $Modal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
